# -*- coding: utf-8 -*-
"""Advanced Visuals in PowerBI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eXNxvopdmkRSvcaKa025l_SXuhamabID

# Advanced Visuals in PowerBI


1. What is the difference between a Basic Filter, Advanced Filter, and a Slicer in Power BI?
- Basic Filter: A checkbox-based filter located in the Filters Pane. It allows you to manually select or deselect specific values (e.g., checking only "2023" from a list of years).  
Advanced Filter: Also located in the Filters Pane, it uses conditional logic to filter data. It allows you to use operators like "Contains", "Starts with", "Is greater than", or "Is blank" to isolate specific data ranges or text patterns.
Slicer: An on-canvas visual element that serves as a user-facing filter. Instead of hiding in the Filters Pane, it sits directly on the report page as a checkbox list, dropdown, slider, or button group, making it highly interactive for end-users.

2. Using the Sales dataset, apply a Basic Filter to display only the sales data for the year 2023.
- Select the visual you want to filter (or click on the empty canvas if you want it to apply to the whole page).
Go to the Filters pane on the right side of the screen.
Drag the Year or Date column from your Sales_dataset fields into the "Filters on this visual" or "Filters on this page" section.  
Change the filter type dropdown to Basic filtering.
Check the box next to 2023.

3. Create a Pie Chart of Sales by Product and add Slicer that allows users to filter the dataset by Region.
- Create the Pie Chart: * Click the Pie Chart icon in the Visualizations pane.
Drag the Product field into the Legend bucket.
Drag the Sales field into the Values bucket.
Add the Slicer:
Click on an empty space on the canvas and select the Slicer icon from the Visualizations pane.  
Drag the Region field into the Field bucket of this slicer.  
Result: Selecting a region in the slicer will dynamically filter the pie chart slices.

4. What is a Visual-Level Filter, and how does it differ from Page-Level and Report-Level Filters?
- Filter ScopeDescription
Visual-Level FilterApplies strictly to a single selected visual on a page. Other charts on the same page remain unaffected.
Page-Level FilterApplies to all visuals across the entire report page you are currently viewing.
Report-Level FilterApplies globally to every single visual across every page in the entire Power BI report file (.pbix).

5. Apply a Report-Level Filter so that all visuals in the Power Bl report display sales only from India.
- Expand the Filters pane on the right side of your canvas.
Scroll down to the section labeled Filters on all pages.  
Drag the Country field from your Sales_dataset and drop it into this section.  
Set the filter type to Basic filtering and check the box for India. Every page in your report will now exclusively show data for India.

6. What is the role of Drill-Down in Power BI? How does it improve data exploration?
- The Drill-Down feature allows users to explore deeper, more granular levels of a data hierarchy within a single visual.  
How it improves exploration: Instead of crowding a dashboard with separate charts for years, quarters, and months, a user can simply click on a specific data point (like a bar representing "2023") to reveal its underlying quarters. It saves canvas space and creates an intuitive, narrative-driven data discovery experience.

7. Using the dataset, create a hierarchy drill-down from Country Region Product Category to analyze sales at different levels.
- Select a visual that supports hierarchies, such as a Clustered Column Chart.
Go to the Visualizations pane and locate the X-axis (or Category) field bucket.
Drag the fields into that single bucket strictly in the following top-to-bottom order:
Country
Region
Product Category
ory

8. Implement Drill-Through so that selecting a Product navigates to a detailed report page showing region-wise sales.
- Create the Target Page: Add a new report page and rename it Product Details.
Set up Drill-Through: On this new page, go to the Visualizations pane, look for the Drill-through section, and drag the Product field into the "Add drill-through fields here" box.  
Build the Detail Visual: On this same page, add a table or matrix chart displaying Region and Sales.  
How to use it: Go back to your main summary page, right-click on any Product data point in your visuals, hover over Drill-through, and click

9. Add a Slicer for Product Category and observe how it interacts with the drill-down hierarchy.
- When you add a Slicer for Product Category alongside your step #7 chart:
The Interaction: Slicers and Drill-downs work together. If you drill down to a specific Region in your chart, and then select a category (e.g., "Electronics") in your slicer, the chart will maintain its drilled-down regional viewpoint but will recalculate the bars to reflect only Electronics sales within those regions.

10. Explain the difference between Drill-Down and Drill-Through in Power Bl using a real-world example.
- Drill-Down (Staying in the same chart to change granularity): * Example: You are looking at a clothing store's yearly sales chart. You click on the "2023" bar, and the chart expands in place to show sales broken down by Q1, Q2, Q3, and Q4. You are changing the time grain of the current view.  
Drill-Through (Moving to a different page for contextual details):
Example: You are looking at a master list of store branches. You right-click on the "Mumbai Branch" and choose to drill through to a specialized Store Performance Dashboard page. This new page shows inventory status, employee count, and customer satisfaction specific only to Mumbai.

11. Use the Drill-Down feature to analyze sales trends from Year Quarter Month Day.
- Create a Line Chart to capture trends over time.
Drag your main Date column into the X-axis bucket. Power BI automatically generates a Date Hierarchy (Year, Quarter, Month, Day) if Auto Date/Time is enabled.  
Drag Sales into the Y-axis bucket.  
Use the "Expand all down one level in the hierarchy" button (the pitchfork icon \Psi\downarrow) in the visual's top menu to view continuous trends moving from Year down to individual Days.

12. Apply a Measure-Based Filter to display only those products where total sales exceed 250,000, Hint: Create a Total Sales measure and apply the filter using the measure, not the Sales column.
- Create the Measure: In the Home tab, click New Measure and write the following DAX formula:
      Total Sales = SUM(Salesataset[Sales]

Create a visual (e.g., a Table visual) and drag Product and your newly created Total Sales measure into it.
With the visual selected, look at the Filters pane.
Under "Filters on this visual", click on your Total Sales measure.
Set the rule to "is greater than" and enter 50000. Click Apply filter.  

13. What is the "Keep All Filters" option in Drill-Through? How does it affect user interaction
- Definition: When setting up a drill-through destination page, there is a toggle switch labeled Keep all filters.  
How it affects interaction: If turned ON (default), any external slicers or filters active on the main summary page (like Year = 2023, Country = India) are passed along to the destination detail page. If turned OFF, only the specific data point you clicked on (e.g., the specific Product) is carried over, wiping out all other background filters.

14. Create a custom Drill-Through page where selecting a Region shows a detailed view of sales trends over time.
- Create a brand new report page named Region Trends.
Select the empty canvas, navigate to the Drill-through pane, and drag the Region field into the drill-through bucket.  
Ensure Keep all filters is enabled if you want to retain global contexts.  
Add a Line Chart to this page with Date (Year/Month) on the X-axis and Sales on the Y-axis to display the timeline trends over time.  
Test it by going to your main page, right-clicking any region name, and drilling through to this page.

15. Design a fully interactive Power BI dashboard using Slicers, Filters, Drill-Down, and Drill-Through to explore sales data.
- To tie all these concepts into a cohesive workspace, follow this visual flow layout:
-------------------------------------------------------------------------+
|  [SLICER: Region]     [SLICER: Product Category]                        |
+-------------------------------------------------------------------------+
|                                    |                                    |
|  1. SALES TRENDS (LINE CHART)      |  2. SALES BY PRODUCT (PIE CHART)   |
|     (Drill-down active:            |     (Right-click a product to      |
|      Year -> Quarter -> Month)      |      Drill-Through to detailed     |
|                                    |      Region Trends page)           |
|                                    |                                    |
+------------------------------------+------------------------------------+
|                                                                         |
|  3. GEOGRAPHIC PERFORMANCE (COLUMN CHART)                              |
|     (Hierarchy active: Country -> Region -> Product Category)           |
|                                                                         |
+-------------------------------------------------------------------------+
|  FILTERS PANE (Hidden/Report-Level): [Country = India]                  |
+-------------------------------------------------------------------------+
"""